### ISSUE TITLE
Cannot find flatblock_tags error

### ISSUE THREAD

**Issue by ggkitsas** [zerok/django-flatblocks#25]
Hello,

I have followed the readme to include flatblocks in my Django project but cannot make it work.

What I get is an exception:
`'flatblock_tags' is not a valid tag library: Template library flatblock_tags not found, tried django.templatetags.flatblock_tags,mptt.templatetags.flatblock_tags,vdr.templatetags.flatblock_tags,promo.templatetags.flatblock_tags,extendedmenus.templatetags.flatblock_tags,custom.satchmo.templatetags.flatblock_tags,django.contrib.staticfiles.templatetags.flatblock_tags,django.contrib.admin.templatetags.flatblock_tags,django.contrib.humanize.templatetags.flatblock_tags,tinymce.templatetags.flatblock_tags,filebrowser.templatetags.flatblock_tags,polymorphic.templatetags.flatblock_tags,polymorphic_tree.templatetags.flatblock_tags,django_wysiwyg.templatetags.flatblock_tags,adminfiles.templatetags.flatblock_tags,flatblocks.templatetags.flatblock_tags,treemenus.templatetags.flatblock_tags,livesettings.templatetags.flatblock_tags,sorl.thumbnail.templatetags.flatblock_tags,compressor.templatetags.flatblock_tags,coffeescript.templatetags.flatblock_tags,pipeline.templatetags.flatblock_tags,notifications.templatetags.flatblock_tags,payments.templatetags.flatblock_tags,crispy_forms.templatetags.flatblock_tags,django_forms_bootstrap.templatetags.flatblock_tags,app_plugins.templatetags.flatblock_tags,zojax.django.forms.templatetags.flatblock_tags,wagtail.wagtailcore.templatetags.flatblock_tags,wagtail.wagtailadmin.templatetags.flatblock_tags,wagtail.wagtailusers.templatetags.flatblock_tags,wagtail.wagtailimages.templatetags.flatblock_tags,wagtail.wagtailembeds.templatetags.flatblock_tags,sass_processor.templatetags.flatblock_tags`

I have installed django-flatblocks (using buildout) and I have added `flatblocks` in `INSTALLED_APPS` in project settings. To validate that flatblocks is installed and found I ran `manage.py help ` and it showed a section about flatblocks:
```
[flatblocks]
    createflatblock
    deleteflatblock
    unassignedflatblocks
```

Not sure where to start debugging the issue, any help will be much appreciated!

**Comment by zerok** [comment]
Hi :) Sorry, but this app is no longer supported. Please try https://github.com/jazzband/django-flatblocks instead :)

**Comment by ggkitsas** [comment]
Hi zerok! I will try it, thank you for the info :)
